### ISSUE TITLE
PageControl

### ISSUE THREAD

**Issue by imclean** [Centroida/SwiftImageCarousel#17]
Where is the page control added to the UI?
I want to get rid of the white background and have it transparent.

Great work!
Thanks.

**Comment by 3257** [comment]
Hey, there, 

thanks for the issue created. 

I just need a little bit of clarification - are you talking about the page control dots added that keep track of the page you are on at the moment? And is it where the pages automatically switch or you zoom them in and out?

Please let me know when you can.

Thanks

**Comment by imclean** [comment]
Hey. 

On the actual page view controller (the main one, not the Gallery), there is a white background to the page control at the bottom (not the dot colours, I can control them through the delegate), I just want to make the image be seen fully underneath the page control (I want it to be transparent, buts its currently opaque). 

Hope that makes sense. I can’t find anywhere where you instantiate and add a control to the view or where a page control is on the storyboard so I can make its background clear. 

Thanks

Iain

**Comment by 3257** [comment]
Your question totally makes sense. 

Let me look into it real quick, now when you have the info I need, and I will write back ASAP today.

**Comment by 3257** [comment]
Actually, I do have the solution for you.

This is really the dirty and quick way to do things:
![screen shot 2017-06-26 at 2 46 37 pm](https://user-images.githubusercontent.com/18184558/27538053-fa409180-5a7e-11e7-874c-0bc14ceb5d6b.png)

**On the other hand, there is a better way**! 
You can use the delegate provided for you with **setupAppearance** function where you can control the appearance of the **first page control** (the one you are talking about) and the appearance of the **second page control** (the one with the **GalleryVC**):

![screen shot 2017-06-26 at 2 58 48 pm](https://user-images.githubusercontent.com/18184558/27538313-062c9b00-5a80-11e7-9451-ab68bfa8ee13.png)

This is directly taken from a project at work where we use the carousel. What you need to do for your project is:
 `firstPageControl.backgroundColor = .clear`

This is also described in the ReadMe file here on GitHub but it is all the way down at the bottom of the file which is why you may have missed it. Sorry about that!

The picture is also not going underneath the page control at this point but I will work on that too!! 

P.S. Could I ask you to star the project if you feel like it indeed 👍

**Comment by 3257** [comment]
P.S. again,

now I do remember I did have an issue with the image going under the dots, and it was because of the default implementation of UIPageControl that does not allow you to do that. I managed to fix it in the GalleryVC when I wanted stuff to be zoomable and etc. 

I think the best way to solve the issue at hand is to provide two options for the actual and initial page view controller - one will be with the default page control background, dots and etc, and one can be the way you need it, with the picture going underneath. 

Let me know if the current solution I have for you in the previous comment worked though.

**Comment by imclean** [comment]
Hi

I’m not at my Mac at the moment, I’m sure I tried changing the appearance though before. And yes I am looking to have the page control over the image so maybe need to look at a full Page Control rather than the free one from UIPageViewController. 

Cheers

Iain

**Comment by 3257** [comment]
Already working on it 👍

**Comment by 3257** [comment]
Ok, the solution we are looking for your case is quite easy but not really good looking. 

In `public class SwiftImageCarouselVC`, add this piece of code:

```swift 
  override public func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        for view in self.view.subviews {
            if view is UIScrollView {
                view.frame = CGRect(x: view.frame.minX , y: view.frame.minY, width: view.frame.width, height: view.frame.height + 37)
            } else if view is UIPageControl {
                view.backgroundColor = .clear
            }
        }
    }
```

No matter whether you imported the framework it as a cocoapod or you added it as a dependency by copying the framework, you can edit the project classes and etc. 

Meanwhile, 

I will update the framework on GitHub and the Cocoapod web site.

**Comment by 3257** [comment]
Codebase and Cocoapod version updated to support function mentioned in issue, Readme file updated. Please star the project if you still like it :) It boosts my ego 🥇 👍

**Comment by imclean** [comment]
I thought about just doing this, agree it’s not nice but certainly achieves the outcome, probably better to use the height of the page control rather than a hard coded value. Knowing Apple, they will change the height soon 😉

Thanks 😊

**Comment by 3257** [comment]
Yeah, it is just a quick fix for now. I plan on soon updating to swift 4 anyways. I do not think there will be much that will change with this particular repo but still :)

**Comment by 3257** [comment]
I am actually fixing it not to be hardcoded but dynamically received value. Thanks for pointing that out. And thanks for the star
